### ISSUE TITLE
Issues with paths including spaces in

### ISSUE THREAD

**Issue by ireicht** [Shadowfen/jshu#1]
Dear Shadowfen,

when testing jshu on my Ubuntu16.1LTS system, I figured some issues:

1) When path to the script contains spaces, then no test-results are produced. This is due to missing quotes in the "`$test_file`" variable in `jshuFinalize()`  (here a diff of jshutest.inc):

`-       echo "\<testsuite failures ... "${total}\">" >${test_file}`
`-       cat $jshu_content_file >>$test_file`
`-       echo "\</testsuite>" >>$test_file`
`+       echo "\<testsuite failures ... "${total}\">" >"${test_file}"`
`+       cat $jshu_content_file >>"$test_file"`
`+       echo "</testsuite>" >>"$test_file"`

2) Also in function jshuRunTests():215, spaces in the path are not interpreted correctly by the command `cd  ${_jshu_run_curdir}` 

quotes fixed this issue (see diff):
`-    cd ${_jshu_run_curdir}`
`+   cd "${_jshu_run_curdir}"`

3) A Segmentation-Fault is caused when executing the `incrbuild_unitTest.sh`. This is most likely due to the function `parseVersion()`. This function is supposed to call function in `parseVersion()` from sourced script `increment_build.sh`. However it ends up in an "infinite" recursion. Renaming `incrbuild_unitTest.sh::parseVersion()` to `incrbuild_unitTest.sh::parseVersion_Test()` solved the issue. If so, then also update content of `jshuTestFunctions="parseVersion getBldFileName_noParam"` to `jshuTestFunctions="parseVersion_Test getBldFileName_noParam"`

regards ireicht

**Comment by Shadowfen** [comment]
Thank you for the patches. I modified the incrbuild_unitTest.sh patch because renaming the parseVersion() function to parseVersionTest() made the function name match the discovery pattern so that it would run once because it was listed in the jshuTestFunctions variable and then a second time because it was automatically discovered as a test function to be executed.

Your modifications have been released in build 17. Thanks again.
